export const AUCTION_CREATE_REQUEST= 'AUCTION_CREATE_REQUEST'
export const AUCTION_CREATE_SUCCESS= 'AUCTION_CREATE_SUCCESS'
export const AUCTION_CREATE_FAIL= 'AUCTION_CREATE_FAIL'
export const AUCTION_CREATE_RESET= 'AUCTION_CREATE_RESET'

export const AUCTION_LATEST_REQUEST= 'AUCTION_LATEST_REQUEST'
export const AUCTION_LATEST_SUCCESS= 'AUCTION_LATEST_SUCCESS'
export const AUCTION_LATEST_FAIL= 'AUCTION_LATEST_FAIL'
export const AUCTION_LATEST_RESET= 'AUCTION_LATEST_RESET'