export const USER_CHECK_REQUEST = 'USER_CHECK_REQUEST'
export const USER_CHECK_SUCCESS = 'USER_CHECK_SUCCESS'
export const USER_CHECK_FAIL = 'USER_CHECK_FAIL'
export const USER_CHECK_RESET = 'USER_CHECK_RESET'

export const CHECK_UPDATE_REQUEST = 'CHECK_UPDATE_REQUEST'
export const CHECK_UPDATE_SUCCESS = 'CHECK_UPDATE_SUCCESS'
export const CHECK_UPDATE_FAIL = 'CHECK_UPDATE_FAIL'
export const CHECK_UPDATE_RESET = 'CHECK_UPDATE_RESET'
