export const USER_FORM_REQUEST = 'USER_FORM_REQUEST'
export const USER_FORM_SUCCESS = 'USER_FORM_SUCCESS'
export const USER_FORM_FAIL = 'USER_FORM_FAIL'
export const USER_FORM_RESET = 'USER_FORM_RESET'

export const USER_FORMLIST_REQUEST = 'USER_FORMLIST_REQUEST'
export const USER_FORMLIST_SUCCESS = 'USER_FORMLIST_SUCCESS'
export const USER_FORMLIST_FAIL = 'USER_FORMLIST_FAIL'
export const USER_FORMLIST_RESET = 'USER_FORMLIST_RESET'

