export const USER_LIVE_REQUEST = 'USER_LIVE_REQUEST'
export const USER_LIVE_SUCCESS = 'USER_LIVE_SUCCESS'
export const USER_LIVE_FAIL = 'USER_LIVE_FAIL'
export const USER_LIVE_RESET = 'USER_LIVE_RESET'

export const USER_LIVELIST_REQUEST = 'USER_LIVELIST_REQUEST'
export const USER_LIVELIST_SUCCESS = 'USER_LIVELIST_SUCCESS'
export const USER_LIVELIST_FAIL = 'USER_LIVELIST_FAIL'
export const USER_LIVELIST_RESET = 'USER_LIVELIST_RESET'

export const LATEST_BID_REQUEST = 'LATEST_BID_REQUEST'
export const LATEST_BID_SUCCESS = 'LATEST_BID_SUCCESS'
export const LATEST_BID_FAIL = 'LATEST_BID_FAIL'
export const LATEST_BID_RESET = 'LATEST_BID_RESET'

export const AUCTION_DELETE_REQUEST= 'AUCTION_DELETE_REQUEST'
export const AUCTION_DELETE_SUCCESS= 'AUCTION_DELETE_SUCCESS'
export const AUCTION_DELETE_FAIL= 'AUCTION_DELETE_FAIL'
export const AUCTION_DELETE_RESET= 'AUCTION_DELETE_RESET'
